jobs:
  Job1:
    name: Job 1
    steps:
      - type: script
        script-content: echo %pwd%
    files-publication:
      - target/test-classes/**/*
secrets:
  pwd: credentialsJSON:7e615871-5073-4a0a-aea3-d38ffaed8cc9
