jobs:
  Job1:
    name: Job 1
    steps:
      - type: script
        script-content: echo %pwd%
      - type: maven
        goals: clean package
    files-publication:
      - target/test-classes/**/*
  Job3:
    name: Job 3
    dependencies:
      - Job1:
          files:
            - target/test-classes/**/*
    steps:
      - type: script
        script-content: echo "Hi!"
secrets:
  pwd: credentialsJSON:7e615871-5073-4a0a-aea3-d38ffaed8cc9
